services:
  - type: web
    name: skipster-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false 